services:
  - type: web
    name: aiwhisper-application
    runtime: python
    buildCommand: ""
    startCommand: uvicorn predictions:app --host 0.0.0.0 --port 10000
    envVars:
    - key: PORT 
      value: 10000